// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGNwWmeXj4NfPkQxV0eNBUb5eWpxHyXmc',
    appId: '1:1072011468843:web:b71a0b0f6db8157a1f0a6e',
    messagingSenderId: '1072011468843',
    projectId: 'moviewiki-3d9a2',
    authDomain: 'moviewiki-3d9a2.firebaseapp.com',
    storageBucket: 'moviewiki-3d9a2.appspot.com',
    measurementId: 'G-V7E64RZBHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKHBHC8_lRvrvYoxKpzfM9jajfz6zBpz4',
    appId: '1:1072011468843:android:5ea78c1a9a6e58401f0a6e',
    messagingSenderId: '1072011468843',
    projectId: 'moviewiki-3d9a2',
    storageBucket: 'moviewiki-3d9a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnA8XVJlF2N5oZw8yyJiGmITE9kaQmWGA',
    appId: '1:1072011468843:ios:4700e0dc96eeecf01f0a6e',
    messagingSenderId: '1072011468843',
    projectId: 'moviewiki-3d9a2',
    storageBucket: 'moviewiki-3d9a2.appspot.com',
    iosBundleId: 'com.example.movieWiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnA8XVJlF2N5oZw8yyJiGmITE9kaQmWGA',
    appId: '1:1072011468843:ios:4700e0dc96eeecf01f0a6e',
    messagingSenderId: '1072011468843',
    projectId: 'moviewiki-3d9a2',
    storageBucket: 'moviewiki-3d9a2.appspot.com',
    iosBundleId: 'com.example.movieWiki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGNwWmeXj4NfPkQxV0eNBUb5eWpxHyXmc',
    appId: '1:1072011468843:web:6432a960fe292e671f0a6e',
    messagingSenderId: '1072011468843',
    projectId: 'moviewiki-3d9a2',
    authDomain: 'moviewiki-3d9a2.firebaseapp.com',
    storageBucket: 'moviewiki-3d9a2.appspot.com',
    measurementId: 'G-VQSWMKTQM2',
  );
}
